name: atproto_bridge_proxy
description: Privately bridges existing platforms to the AT Protocol
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  atproto: ^0.8.0
  base_codecs: ^1.0.1
  bluesky: ^0.10.0
  dart_twitter_api: ^0.5.8
  faker: ^2.1.0
  html2md: ^1.3.1
  html_unescape: ^2.0.0
  http: ^1.1.0
  logger: ^2.0.2+1
  mastodon_api: ^0.6.1
  path: ^1.8.3
  quiver: ^3.2.1
  thirds: ^0.2.0-alpha.1
  alfred: ^1.1.1
  draw: ^1.1.0
  lib5: ^0.1.0
  nostr: ^1.4.0
  bech32: ^0.2.2
  youtube_explode_dart: ^2.0.2
  xml2json: ^6.2.0
  html_character_entities: ^1.0.0+1
  intl: ^0.17.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

dependency_overrides:
  http: 1.1.0